config/routes.rb
Rails.application.routes.draw do
  
  
  # get '/movies', to: 'movies#index'
  # get '/movies/new', to:'movies#new'
  # get '/movies/:id', to: 'movies#show', as: 'movie'
  # get '/movies/:id/edit', to: 'movies#edit', as: 'edit_movie'
  # patch '/movies/:id', to: 'movies#update'
  # post '/movies', to: 'movies#create'
  # delete '/movies/:id', to: 'movies#destroy'
  get 'session/create'
  root to: 'movies#index'
  get 'movies/filter/:filter', to: 'movies#index', as: :filtered_movies
  resources :movies do
    resources :reviews
    resources :favs, only: [:create]
  end
  
  get 'sign_up', to:'users#new'
  resources :users, except: [:new]

  resource :session, only: [:create,:destroy]
  get '/sign_in', to:'sessions#new', as: :sign_in
  get '/sign_out',to: 'sessions#sign_out', as: :sign_out
  
  # resources :favs, only: [:destroy]
  delete 'movies/:id/favs', to: 'favs#destroy'

end


# get 'session/create'
#   get '/sign_in', to: 'session#new'
#   root to: 'movies#index'
#   resources :users, except: [:new]
#   get '/sign_up', to: 'users#new'
#   resources :movies do
#     resources :reviews
#   end

#   resources :reviews, only: [:destroy]

#   resources :session, only: [:create, :destroy]
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/movie.rb
class Movie < ApplicationRecord

	has_many :reviews, dependent: :destroy
	has_many :favs, dependent: :destroy
	has_many :users, through: :favs
	has_many :genre_categorizations, dependent: :destroy
	has_many :genres, through: :genre_categorizations

	RATINGS = %w(G PG PG-13 R NC-17)

	validates :title, :released_on, :duration, presence: true
	validates :description , length: { minimum: 25 }
	validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
	# validates :image_file_name, format: { with: /\w+\.(jpg|png)\z/i, message: "Must be a PNG or JPG file" }
	validates :rating, inclusion: RATINGS 

	scope :released, -> { where("released_on < ?", Time.now).order("released_on desc") }
	scope :upcoming, -> { where("released_on > ?", Time.now).order("released_on asc") }
	scope :recent, -> { released.limit(4) }
	scope :hit, -> { where("total_gross > ?", 300000000) }
	scope :flop, -> { where("total_gross < ?", 225000000) }

	has_one_attached :poster
	validate :acceptable_poster

	before_save :set_slug

	def set_slug
		self.slug = to_param
	end

	def low_total_gross?
		total_gross < 225000000
	end

	def average_stars
		Review.where(movie_id: self.id).average(:stars)
	end

	def cult_movie?
		self.reviews.size > 6 && average_stars >= 0.4
	end

	def fav_count
		favs.count
	end

	def favoured_by?(user)
		favs.exists?(user: user)
	end

	def to_param
		title.parameterize
	end

	private
	def acceptable_poster
		return unless poster.attached?
		if poster.byte_size >= 1.megabyte
			errors.add(:poster, "file size is too big to upload")
		end

		acceptable_poster_type = ["image/jpeg", "image/png"]
		unless acceptable_poster_type.include? poster.content_type
			errors.add(:poster, "must be a jpg or png file")
		end
	end



	
	# def self.released
	# 	where("released_on < ?", Time.now)
	# end

	# def self.hit_movies
	# 	where("total_gross > ?", 300000000)
	# end
	
	# def self.flop_movies
	# 	where("total_gross < ?", 225000000)
	# end

	# def self.recently_added
	# 	order("released_on desc").limit(3)
	# end

	# def self.upcoming
	# 	where("released_on > ?", Time.now)
	# end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  add_flash_types :notice, :alert
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    # @movies = Movie.all
    # puts "Query: #{Movie.released.to_sql}" 
    filter = params[:filter]
    case filter
    when "upcoming"
      @movies = Movie.upcoming
    when "recent"
      @movies = Movie.recent
    else
      @movies = Movie.released
    end

  end

  def show
    # @movie = Movie.find(params[:id])
    @review = @movie.reviews.new
    
  end

  def edit
    # @movie = Movie.find(params[:id])
  end

  def update
    # @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      flash[:notice] = "Movie updated successfully!"
      redirect_to @movie
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie created successfully!"
    else
      render :new
    end
  end

  def destroy
    # @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path, alert: "Movie is deleted"
  end


  private

  def set_movie
    @movie = Movie.find_by(slug: params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :total_gross, :released_on, :director, :duration, :poster, genre_ids: [])
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
	def success_state(movie)
		if movie.total_gross.present?
			if movie.low_total_gross? 
				"Flop"
			else
				number_to_currency(movie.total_gross, precision:2)
			end
		end
	end

	def movie_poster(movie, action)
		if movie.poster.attached?
			if action == "show"
				image_tag movie.poster.variant(resize_to_limit: [1000,1000])
			elsif action == "index"
				image_tag movie.poster.variant(resize_to_limit: [200,200])
			end
		else
			image_tag 'placeholder.png'
		end
	end

end

app/views/movies/_form.html.erb
<%= render 'shared/errors', object: movie %>

<%= form_with(model: movie, local:true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :rating %>
    <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>

    <%= f.label :total_gross %>
    <%= f.text_field :total_gross %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 4 %>

    <%= f.label :released_on %>
    <%= f.date_select :released_on %>

    <%= f.label :director %>
    <%= f.text_field :director %>

    <%= f.label :duration %>
    <%= f.text_field :duration %>

    <%= f.label :genre %>
    <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name %>

    <%= f.label :poster %>
    <%= f.file_field :poster %>

    <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
  <div>
    <h2><u>Movie Collection:</u></h2> 
    <%= link_to 'Awaiting for Release', filtered_movies_path("upcoming") %> | 
    <%= link_to 'Recent Release', filtered_movies_path("recent") %>
    <div class= "align_right" style = "margin-left: 736px;">
      <% if current_user_admin? %>
        <%= link_to '+Add Movie to Collection', new_movie_path %>      
      <% end %>
  </div>
  </div>
  <br>
  <ol>
    <% @movies.each do |movie|%>
      <section class="movie">
        <div class="summary">
          <h2>
            <li><b> <%= link_to movie.title.capitalize, movie_path(movie) %></b> (<%= movie.rating%>)...</li>
          </h2>	
          <h3>
            <%= success_state(movie) %>
          </h3>
          <p>
            <%= truncate(movie.description, length: 150, separator: ' ') %>
          </p>
          <h6>Poster:</h6>
            <%= movie_poster(movie, "index") %>
          <p>
            <b>Average Rating:</b> <%= average_rating(movie) %>
          </p>
        </div>
      </section>
    <% end %>
  </ol>
  
    

app/views/movies/new.html.erb
<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<div>
    <center>
        <h1>Movie Details</h1> 
        <% if @movie.favoured_by?(current_user)%>
            <%= button_to "❤️ (#{@movie.fav_count})", movie_favs_path(@movie), method: :delete, class: :button %>
        <% else %>
            <%= button_to "🤍 (#{@movie.fav_count})", movie_favs_path(@movie), method: :post, class: :button %>
        <% end %>
    </center> 
    <br>
    <center><%= link_to 'Check Reviews ⭐', movie_reviews_path(@movie) %> | <%= link_to 'Give Review ✍️', new_movie_review_path(@movie) %></center> 
    <div class= "align_right" style = "margin-left: -128px;"><%= link_to '<< Back to Collection', movies_path %></div>
    <br>
    <ul>
        <li><p><b>Title:</b> <%= @movie.title %></p></li>
        <li><p><b>Rating:</b> <%= @movie.rating %></p></li>
        <li><p><b>Gross detail:</b> <%= success_state(@movie) %></p></li>
        <li><p><b>Description:</b> <%= @movie.description %></p></li>
        <li><p><b>Released:</b> <%= @movie.released_on.strftime("%B %dth on %A - %H:%m %p") %></p></li>
        <li><p><b>Director:</b> <%= @movie.director %></p></li>
        <li><p><b>Duration:</b> <%= @movie.duration %></p></li>
        <li><p><b>Official Poster:</b> </br></br><%= movie_poster(@movie, "show") %></p></li>
        <li><p><b>Genre:</b>
            <ul>
                <% @movie.genres.each do |genre| %>
                    <li><%= genre.name %></li>
                <% end %>
            </ul>
        </p></li>
    </ul>
    <br><br>
    <%= render '/reviews/form', review: @review %>
    <br><br>
    <center><%= link_to 'Edit Movie Details', edit_movie_path(@movie) %> | <%= link_to 'Delete Movie From Collection', movie_path(@movie), method: :delete, data: {confirm: "Are you sure you want to delete movie from collection?"} %></center> 
    
</div>