config/routes.rb
Rails.application.routes.draw do
  
  
  # get '/movies', to: 'movies#index'
  # get '/movies/new', to:'movies#new'
  # get '/movies/:id', to: 'movies#show', as: 'movie'
  # get '/movies/:id/edit', to: 'movies#edit', as: 'edit_movie'
  # patch '/movies/:id', to: 'movies#update'
  # post '/movies', to: 'movies#create'
  # delete '/movies/:id', to: 'movies#destroy'
  get 'session/create'
  root to: 'movies#index'
  get 'movies/filter/:filter', to: 'movies#index', as: :filtered_movies
  resources :movies do
    resources :reviews
    resources :favs, only: [:create]
  end
  
  get 'sign_up', to:'users#new'
  resources :users, except: [:new]

  resource :session, only: [:create,:destroy]
  get '/sign_in', to:'sessions#new', as: :sign_in
  get '/sign_out',to: 'sessions#sign_out', as: :sign_out
  
  # resources :favs, only: [:destroy]
  delete 'movies/:id/favs', to: 'favs#destroy'

end


# get 'session/create'
#   get '/sign_in', to: 'session#new'
#   root to: 'movies#index'
#   resources :users, except: [:new]
#   get '/sign_up', to: 'users#new'
#   resources :movies do
#     resources :reviews
#   end

#   resources :reviews, only: [:destroy]

#   resources :session, only: [:create, :destroy]
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/_flash.html.erb
<% if flash.any? %>	
	<% flash.each do |type, message| %>
		<div class = "flash <%= type%>">
			<%= message %>
		</div>
	<% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <%= image_tag 'logo.png' %>
    <% if current_user.present? %>
        <div style= "color: whitesmoke;">Welcome <%= current_user.user_name.capitalize %>!</div>
        <%= link_to 'Movies', movies_path, style: "color: whitesmoke;" %> |
        <%= link_to 'My Profile', user_path(current_user), style: "color: whitesmoke;"  %> |
        <%= link_to 'Account Settings', edit_user_path(current_user), style: "color: whitesmoke;" %> |
        <%= link_to 'SignOut', sign_out_path(current_user), style: "color: whitesmoke;" %>
        
    <% end %>   
     
     <% if !current_user %>
        <h6><%= link_to 'SignUp!', sign_up_path, style: "color: whitesmoke;" %> | <%= link_to 'Sign In', sign_in_path, style: "color: whitesmoke;" %> | <%= link_to 'Users', users_path, style: "color: whitesmoke;" %></h6>
    <% end %>
    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= render "layouts/flash" %>
    <div class="content">
      <%= yield %>
    </div>
    <footer>©️
      <b><%= link_to "Copyright #{Time.now.year}", movies_path %></b> Flix</footer>
  </body>
</html>